server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # DB Setting
  data:
    redis:
      host: localhost
      port: 6379

  # Rabbitmq Setting
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest